/**
 * @packageDocumentation
 * Rule: require-isolated-declarations
 */
import type { JsoncRuleModule } from "../_internal/jsonc-rule.js";

import { createJsoncRule } from "../_internal/jsonc-rule.js";

/** Rule implementation for this tsconfig lint rule. */
const rule: JsoncRuleModule = createJsoncRule({
    create() {
        return {
            JSONObjectExpression() {},
        };
    },
    meta: {
        docs: {
            description:
                "require `isolatedDeclarations: true` so declaration files can be emitted without type resolution.",
            recommended: false,
            requiresTypeChecking: false,
            tsconfigConfigs: [
                "all",
                "emit-config",
                "strictest",
            ],
        },
        fixable: "code",
        messages: {
            missingIsolatedDeclarations:
                '`isolatedDeclarations: true` (introduced in TypeScript 5.5) requires all exported declarations to have explicit type annotations, enabling declaration files to be generated by fast single-file tools (esbuild, oxc-transform, SWC) without full type resolution. This is strongly recommended for libraries. Add `"isolatedDeclarations": true` to `compilerOptions`.',
        },
        schema: [],
        type: "suggestion",
    },
    name: "require-isolated-declarations",
});

export default rule;
