import { isDefined } from "ts-extras";

/**
 * @packageDocumentation
 * Rule: require-isolated-declarations
 */
import type {
    JSONObjectExpression,
    JSONProperty,
} from "../_internal/jsonc-helpers.js";
import type { JsoncRuleModule } from "../_internal/jsonc-rule.js";

import {
    findProperty,
    getBooleanValue,
    getCompilerOptions,
    insertProperty,
    replacePropertyValue,
    reportViolation,
} from "../_internal/jsonc-helpers.js";
import { createJsoncRule } from "../_internal/jsonc-rule.js";
import { createRuleDocsUrl } from "../_internal/rule-docs-url.js";

/** Rule implementation for this tsconfig lint rule. */
const rule: JsoncRuleModule = createJsoncRule({
    create(context) {
        return {
            JSONObjectExpression(node: Readonly<JSONObjectExpression>) {
                if (node.parent?.type !== "JSONExpressionStatement") return;
                const co = getCompilerOptions(node);
                if (!co) return;

                const prop: JSONProperty | undefined = findProperty(
                    co,
                    "isolatedDeclarations"
                );

                if (isDefined(prop) && getBooleanValue(prop) === true) return;

                reportViolation(context, {
                    fix(fixer) {
                        if (isDefined(prop)) {
                            return replacePropertyValue(fixer, prop, true);
                        }
                        return insertProperty(
                            fixer,
                            co,
                            "isolatedDeclarations",
                            true
                        );
                    },
                    loc: (prop ?? co).loc,
                    messageId: "missingIsolatedDeclarations",
                });
            },
        };
    },
    meta: {
        docs: {
            description:
                "require `isolatedDeclarations: true` so declaration files can be emitted without type resolution.",
            recommended: false,
            requiresTypeChecking: false,
            tsconfigConfigs: [
                "all",
                "emit-config",
                "strictest",
            ],
            url: createRuleDocsUrl("require-isolated-declarations"),
        },
        fixable: "code",
        messages: {
            missingIsolatedDeclarations:
                '`isolatedDeclarations: true` (introduced in TypeScript 5.5) requires all exported declarations to have explicit type annotations, enabling declaration files to be generated by fast single-file tools (esbuild, oxc-transform, SWC) without full type resolution. This is strongly recommended for libraries. Add `"isolatedDeclarations": true` to `compilerOptions`.',
        },
        schema: [],
        type: "suggestion",
    },
    name: "require-isolated-declarations",
});

export default rule;
